start
:Visitor kiest ervoor om een account aan te maken;

repeat
	:Visitor voert zijn gebruikersnaam en wachtwoord in;
	:Systeem valideert de gegevens;
repeat while (Juiste gegevens?) is (nee)
->ja;

:Systeem maakt account aan;
:Systeem geeft de speler een startsaldo van 1000 credits;
stop