@startuml
!theme plain
skinparam style strictuml

title startQuiz

actor "currentPlayer:Player" as player

player -> "parola:ParolaController" ++ : startQuiz(username)

"parola:ParolaController" -> "parolaService:ParolaService" ++--: startQuiz(username)
ref over "parolaService:ParolaService", "currentPlayer:Player" :Register
"parolaService:ParolaService" -> "qh:QuizHandler" ** : create
"parolaService:ParolaService" -> "qh:QuizHandler" ++: currentQuiz = getQuiz()
"qh:QuizHandler" -> "timer:Timer" ** : create
"qh:QuizHandler"-> "timer:Timer" --: startTimer()

"parolaService:ParolaService" -> "qh:QuizHandler" : purchase_amount = getPurchaseAmount()

"parolaService:ParolaService" -> "currentPlayer:Player" : deductCredits(purchase_amount)


@enduml